# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff7fe5b4a50a09a7b1662dbabaaff8aae79cb4fdd9dc511aa0e59c20d2002dd7b7739818dec7b066b46964100becc6cab41e139375a0e7a1083ecd58dd237b40

test:
  secret_key_base: a8e0a3ad2555411a4370b574087025b636d71e9843d04426451b6f5608df3e68a02368629847fc4f47cbccedc105222f2529a2624327283fd20c2151088af6d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
